// ===============================================================
// WF4 - Lawyer Review & Approval
// Node: "Build Review Email"  (Code -> Run Once for All Items)
//
// Composes the notification a reviewer receives, and pre-builds the
// parameter array for the Postgres INSERT that follows.
//
// Why a Code node instead of writing the body inline in the SQL
// node: the body is multi-line text stitched from two upstream
// nodes plus a runtime URL. Expressed as one n8n expression it
// would be unreadable and untestable. Here it is plain JS, lives in
// git, and the next node just consumes $json.params.
// ===============================================================

// Bug #1: a Postgres node REPLACES its input. "Create Review
// Request" returned only the four RETURNING columns, so the clause
// details are gone from $json. Reach back to the node that had them.
const clause = $('Fetch Clause').first().json;
const request = $('Create Review Request').first().json;

// The form URL is generated by n8n at run time and is unique to
// THIS execution. Reading it here - before the flow reaches the
// Wait node - is what lets the email carry a working link.
const formUrl = $execution.resumeFormUrl;

// Read from the environment, never hardcoded. A different
// deployment reviews with a different lawyer and only changes .env.
const toAddress = $env.REVIEW_EMAIL;

if (!toAddress) {
  // Fail loudly. A silently missing recipient would create a review
  // request that no human is ever told about, and the execution
  // would sit waiting forever.
  throw new Error(
    'REVIEW_EMAIL is not set. Add it to .env and restart the container.'
  );
}

// Human-readable explanation of WHY this clause was routed. The
// routing rule is evidence-based, so the email states the evidence
// rather than a bare number - a lawyer can act on "we could not
// find this text in the contract"; they cannot act on "0.75".
const attribution = clause.attribution || 'unknown';
let reason;

if (attribution === 'not_found') {
  reason =
    'The model returned this clause text, but it could NOT be located ' +
    'anywhere in the source document. It is most likely a paraphrase ' +
    'rather than a verbatim quote. Please check the contract and either ' +
    'approve it, correct it with the true wording, or reject it.';
} else if (clause.is_absent === true) {
  reason =
    'The model reported that this clause type is ABSENT from the ' +
    'contract, and the risk of that being wrong is high ' +
    '(risk score ' + clause.risk_score + '). Please confirm the clause ' +
    'is genuinely missing.';
} else {
  reason = 'This clause was flagged for manual review.';
}

const subject =
  '[Clause Review] ' + clause.clause_type + ' - ' + clause.filename;

// Plain text, not HTML. The outbox row is read by a human during the
// demo and later by a Gmail node; plain text renders correctly in both.
const bodyText = [
  'A clause extraction needs your review.',
  '',
  'Document      : ' + clause.filename,
  'Clause type   : ' + clause.clause_type,
  'Risk level    : ' + clause.risk_level + ' (score ' + clause.risk_score + ')',
  'Model conf.   : ' + clause.confidence,
  'Attribution   : ' + attribution,
  '',
  'Why you are seeing this:',
  reason,
  '',
  '--- Extracted clause text ---',
  clause.clause_text || '(the model reported this clause as absent)',
  '--- end ---',
  '',
  'Record your decision here:',
  formUrl,
  '',
  'On the form:',
  '  approve  - the extraction is correct as-is',
  '  correct  - paste the true clause wording into "Corrected clause text"',
  '  reject   - this is not a valid instance of this clause type',
  '',
  'Review request #' + request.review_request_id +
  ' (token ' + request.token + ')',
].join('\n');

// Bug #2: the Query Parameters field splits a plain string on
// commas, which would shred any clause text containing a comma.
// Building the array here and passing it bare as {{ $json.params }}
// sidesteps the splitter entirely.
return [
  {
    json: {
      review_request_id: request.review_request_id,
      token: request.token,
      clause_id: request.clause_id,
      document_id: request.document_id,
      form_url: formUrl,
      params: [
        'clause_review',                      // $1 purpose
        Number(request.review_request_id),    // $2 review_request_id
        Number(request.document_id),          // $3 document_id
        toAddress,                            // $4 to_address
        subject,                              // $5 subject
        bodyText,                             // $6 body_text
      ],
    },
  },
];
