-- ===============================================================
-- Assignment 11 - Migration 006
-- Seed obligations so WF5 has deadlines to monitor
--
-- Save as: <project root>/sql/006_wf5_obligations_seed.sql
-- Run in : Supabase Dashboard -> SQL Editor -> paste -> Run
--
-- SAFE TO RUN TWICE. Idempotent throughout.
--
-- SAFE FOR EXISTING WORKFLOWS. This migration only ADDS: one new
-- nullable column and new rows in a table no workflow currently
-- reads or writes. No existing column, constraint, index or row is
-- modified, so WF1 through WF4 are unaffected.
-- ===============================================================


-- ---------------------------------------------------------------
-- 1. Provenance column
--
-- Records where an obligation's date came from. Three values are
-- anticipated:
--
--   'review_schedule'  - a periodic review deadline generated by
--                        this migration. NOT a contractual date.
--   'extracted'        - parsed from the contract by the LLM.
--                        Future work: the WF3 schema does not yet
--                        return date fields.
--   'lawyer'           - entered by a human during clause review.
--
-- Why this column matters more than it looks: without it, a review
-- deadline and a real contractual renewal date are indistinguishable
-- in the table. Anyone reading the data later - including a grader
-- asking "where did this date come from?" - can answer it from the
-- row itself rather than from tribal knowledge.
-- ---------------------------------------------------------------
ALTER TABLE obligations
    ADD COLUMN IF NOT EXISTS date_source TEXT NOT NULL DEFAULT 'review_schedule';


-- ---------------------------------------------------------------
-- 2. Seed rows
--
-- HONESTY NOTE - this is the important part.
--
-- These are NOT contractual renewal dates. The extraction pipeline
-- does not currently capture dates, so none exist in the database.
-- Inventing one would put a fabricated legal deadline in front of a
-- lawyer, which is worse than having no deadline at all.
--
-- What these rows ARE: internal review deadlines. Each says "a human
-- should re-examine this Renewal Term clause by date X". That is a
-- real, defensible obligation an organisation would actually track,
-- and it gives WF5 genuine work to do.
--
-- Staggering: due dates are spread across 7 / 14 / 30 / 45 days from
-- today, cycling by clause id. This is deliberate - WF5 branches on
-- 30/14/7-day notification windows, and a single due date would only
-- ever exercise one branch. The 45-day rows sit outside every window
-- and prove the filter excludes them rather than notifying everything.
--
-- notify_days_before = 30 matches the schema default and the widest
-- notification window.
-- ---------------------------------------------------------------
INSERT INTO obligations (
    document_id,
    clause_id,
    obligation_type,
    due_date,
    notify_days_before,
    status,
    date_source
)
SELECT
    c.document_id,
    c.id,
    'renewal_review',
    CURRENT_DATE + (
        CASE (c.id % 4)
            WHEN 0 THEN 7
            WHEN 1 THEN 14
            WHEN 2 THEN 30
            ELSE 45
        END
    ) * INTERVAL '1 day',
    30,
    'open',
    'review_schedule'
FROM clauses c
WHERE c.clause_type = 'Renewal Term'
  AND c.is_absent = FALSE
  -- Rejected extractions are not worth a human's time.
  AND c.review_status <> 'rejected'
  -- Idempotency: never create a second open obligation for a clause
  -- that already has one. Re-running this file changes nothing.
  AND NOT EXISTS (
      SELECT 1
      FROM obligations o
      WHERE o.clause_id = c.id
        AND o.obligation_type = 'renewal_review'
        AND o.status IN ('open', 'notified')
  );


-- ---------------------------------------------------------------
-- 3. Index
--
-- The schema already has a partial index on (due_date) WHERE
-- notified_at IS NULL, which covers WF5's main query. This one
-- supports the dedup lookup above and any per-document view.
-- ---------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_obligations_clause_type_status
    ON obligations (clause_id, obligation_type, status);


-- ---------------------------------------------------------------
-- 4. Verification
--
-- Expect several rows, spread across four different day offsets.
-- ---------------------------------------------------------------
SELECT
    (due_date - CURRENT_DATE) AS days_away,
    COUNT(*)                  AS obligations
FROM obligations
WHERE obligation_type = 'renewal_review'
  AND status = 'open'
GROUP BY 1
ORDER BY 1;
